version: '3'

services:
  ### APP ###
  mc-server-control-discord-bot:
    build: .
    container_name: mc-server-control-discord-bot
    restart: always
    environment:
      - GCP_CREDS_JSON_BASE64=${GCP_CREDS_JSON_BASE64}
      - BOT_TOKEN=${BOT_TOKEN}
      - MC_SERVER_IP=${GCP_MC_SV_IP}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
